/* eslint-disable */
require('dotenv').config();
const { Pool } = require('pg');

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

// Today for all date calculations: 2026-06-03
const TODAY = '2026-06-03';
const NOW = new Date().toISOString();

// ---------------------------------------------------------------------------
// Plans
// ---------------------------------------------------------------------------
const PLANS = [
  {
    name: 'Completo',
    meals: ['breakfast', 'morning_snack', 'salad', 'lunch', 'afternoon_snack', 'dinner', 'juice'],
    price: 3500,
  },
  {
    name: 'Ligero',
    meals: ['breakfast', 'salad', 'lunch', 'juice'],
    price: 2000,
  },
  {
    name: 'Básico',
    meals: ['salad', 'lunch', 'juice'],
    price: 1500,
  },
  {
    name: 'Ejecutivo',
    meals: ['salad', 'lunch', 'afternoon_snack', 'juice'],
    price: 1800,
  },
  {
    name: 'Premium',
    meals: [
      'breakfast',
      'morning_snack',
      'salad',
      'lunch',
      'afternoon_snack',
      'dinner',
      'juice',
      'extra',
    ],
    price: 4200,
  },
];

// ---------------------------------------------------------------------------
// Client definitions
// ---------------------------------------------------------------------------

// 25 active clients — isActive true, contractEndDate in the future
const ACTIVE_CLIENTS = [
  // id: 1  — plain active
  {
    name: 'Carlos Mendoza',
    sex: 'male',
    dateOfBirth: '1985-03-12',
    phoneNumber: '71234567',
    address: 'Av. Arce 1450, Piso 3',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['gluten'],
    isActive: true,
    plan: 'Completo',
    discount: 0,
    contractDate: '2026-03-01',
    startDate: '2026-03-03',
    contractEndDate: '2026-08-01',
    duration: 110,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-03-01', metadata: { plan: 'Completo', price: 3500 } }],
  },
  // id: 2
  {
    name: 'Ana García',
    sex: 'female',
    dateOfBirth: '1992-07-25',
    phoneNumber: '72345678',
    address: 'Calle Potosí 890',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: ['diabetes'],
    restrictions: ['azúcar refinada', 'frituras'],
    isActive: true,
    plan: 'Ligero',
    discount: 100,
    contractDate: '2026-02-15',
    startDate: '2026-02-17',
    contractEndDate: '2026-09-15',
    duration: 150,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-02-15', metadata: { plan: 'Básico', price: 1500 } },
      { eventType: 'plan_changed', occurredAt: '2026-04-01', metadata: { previousPlan: 'Básico', newPlan: 'Ligero', newPrice: 2000 } },
    ],
  },
  // id: 3
  {
    name: 'José Rivera',
    sex: 'male',
    dateOfBirth: '1978-11-05',
    phoneNumber: '73456789',
    address: 'Calle Murillo 230',
    deliveryZone: 'Sur',
    delivery: 'Otro',
    nit: '4567891',
    businessName: 'Rivera e Hijos S.R.L.',
    underlyingDiseases: ['hipertensión'],
    restrictions: ['sodio', 'embutidos'],
    isActive: true,
    plan: 'Ejecutivo',
    discount: 200,
    contractDate: '2026-01-20',
    startDate: '2026-01-22',
    contractEndDate: '2026-07-22',
    duration: 130,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-01-20', metadata: { plan: 'Ejecutivo', price: 1800 } },
      { eventType: 'plan_changed', occurredAt: '2026-03-15', metadata: { previousPlan: 'Ejecutivo', newPlan: 'Ejecutivo', newPrice: 1600 } },
    ],
  },
  // id: 4  — was paused and resumed
  {
    name: 'María López',
    sex: 'female',
    dateOfBirth: '1990-05-18',
    phoneNumber: '74567890',
    address: 'Av. Santiváñez 720',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['lactosa'],
    isActive: true,
    plan: 'Básico',
    discount: 0,
    contractDate: '2026-01-10',
    startDate: '2026-01-12',
    contractEndDate: '2026-08-30',
    duration: 170,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-01-10', metadata: { plan: 'Básico', price: 1500 } },
      { eventType: 'paused', occurredAt: '2026-03-01', metadata: { remainingDays: 80 } },
      { eventType: 'resumed', occurredAt: '2026-03-20', metadata: { newContractEndDate: '2026-08-30' } },
    ],
  },
  // id: 5
  {
    name: 'Luis Pérez',
    sex: 'male',
    dateOfBirth: '1988-08-30',
    phoneNumber: '75678901',
    address: 'Calle Ingavi 345',
    deliveryZone: 'Sur',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: [],
    isActive: true,
    plan: 'Premium',
    discount: 500,
    contractDate: '2026-04-01',
    startDate: '2026-04-02',
    contractEndDate: '2026-10-01',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-04-01', metadata: { plan: 'Premium', price: 4200 } }],
  },
  // id: 6  — was paused and resumed
  {
    name: 'Carmen Rodríguez',
    sex: 'female',
    dateOfBirth: '1983-01-14',
    phoneNumber: '76789012',
    address: 'Av. Heroínas 560',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: ['gastritis'],
    restrictions: ['picante', 'cítricos'],
    isActive: true,
    plan: 'Ligero',
    discount: 150,
    contractDate: '2026-02-01',
    startDate: '2026-02-03',
    contractEndDate: '2026-09-01',
    duration: 155,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-02-01', metadata: { plan: 'Ligero', price: 2000 } },
      { eventType: 'paused', occurredAt: '2026-04-10', metadata: { remainingDays: 95 } },
      { eventType: 'resumed', occurredAt: '2026-04-25', metadata: { newContractEndDate: '2026-09-01' } },
    ],
  },
  // id: 7
  {
    name: 'Miguel Ramírez',
    sex: 'male',
    dateOfBirth: '1995-09-22',
    phoneNumber: '77890123',
    address: 'Calle Bolívar 112',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['mariscos'],
    isActive: true,
    plan: 'Completo',
    discount: 0,
    contractDate: '2026-04-15',
    startDate: '2026-04-16',
    contractEndDate: '2026-10-15',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-04-15', metadata: { plan: 'Completo', price: 3500 } }],
  },
  // id: 8
  {
    name: 'Isabel Martínez',
    sex: 'female',
    dateOfBirth: '1987-12-03',
    phoneNumber: '78901234',
    address: 'Av. América 780',
    deliveryZone: 'Sur',
    delivery: 'Otro',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['nueces', 'maní'],
    isActive: true,
    plan: 'Ejecutivo',
    discount: 0,
    contractDate: '2026-03-20',
    startDate: '2026-03-21',
    contractEndDate: '2026-09-20',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-03-20', metadata: { plan: 'Ejecutivo', price: 1800 } }],
  },
  // id: 9
  {
    name: 'Fernando Ortega',
    sex: 'male',
    dateOfBirth: '1980-04-07',
    phoneNumber: '79012345',
    address: 'Calle Sucre 450',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: '1234567',
    businessName: 'Ortega Consulting',
    underlyingDiseases: ['colesterol alto'],
    restrictions: ['carnes rojas', 'embutidos'],
    isActive: true,
    plan: 'Ligero',
    discount: 200,
    contractDate: '2026-05-01',
    startDate: '2026-05-02',
    contractEndDate: '2026-11-01',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-05-01', metadata: { plan: 'Ligero', price: 2000 } }],
  },
  // id: 10
  {
    name: 'Laura Sánchez',
    sex: 'female',
    dateOfBirth: '1993-02-28',
    phoneNumber: '70123456',
    address: 'Av. Blanco Galindo km 2',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['soja'],
    isActive: true,
    plan: 'Básico',
    discount: 0,
    contractDate: '2026-04-20',
    startDate: '2026-04-21',
    contractEndDate: '2026-10-20',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-04-20', metadata: { plan: 'Básico', price: 1500 } }],
  },
  // id: 11 — reactivated (finalized before, now active again)
  {
    name: 'Roberto Núñez',
    sex: 'male',
    dateOfBirth: '1975-06-15',
    phoneNumber: '71111222',
    address: 'Calle Colombia 890',
    deliveryZone: 'Sur',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: [],
    isActive: true,
    plan: 'Completo',
    discount: 0,
    contractDate: '2026-05-10',
    startDate: '2026-05-12',
    contractEndDate: '2026-11-10',
    duration: 130,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2025-10-01', metadata: { plan: 'Básico', price: 1500 } },
      { eventType: 'finalized', occurredAt: '2026-01-15', metadata: {} },
      { eventType: 'reactivated', occurredAt: '2026-05-10', metadata: {} },
      { eventType: 'plan_assigned', occurredAt: '2026-05-10', metadata: { plan: 'Completo', price: 3500 } },
    ],
  },
  // id: 12 — reactivated
  {
    name: 'Patricia Torres',
    sex: 'female',
    dateOfBirth: '1989-10-11',
    phoneNumber: '72222333',
    address: 'Av. Tadeo Haenke 230',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: ['anemia'],
    restrictions: ['alimentos procesados'],
    isActive: true,
    plan: 'Premium',
    discount: 300,
    contractDate: '2026-05-05',
    startDate: '2026-05-06',
    contractEndDate: '2026-11-05',
    duration: 130,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2025-09-15', metadata: { plan: 'Ligero', price: 2000 } },
      { eventType: 'finalized', occurredAt: '2025-12-20', metadata: {} },
      { eventType: 'reactivated', occurredAt: '2026-05-05', metadata: {} },
      { eventType: 'plan_assigned', occurredAt: '2026-05-05', metadata: { plan: 'Premium', price: 4200 } },
    ],
  },
  // id: 13
  {
    name: 'Diego Castillo',
    sex: 'male',
    dateOfBirth: '1997-03-19',
    phoneNumber: '73333444',
    address: 'Calle Jordán 120',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: [],
    isActive: true,
    plan: 'Básico',
    discount: 0,
    contractDate: '2026-05-15',
    startDate: '2026-05-16',
    contractEndDate: '2026-11-14',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-05-15', metadata: { plan: 'Básico', price: 1500 } }],
  },
  // id: 14
  {
    name: 'Sofía Herrera',
    sex: 'female',
    dateOfBirth: '1991-08-06',
    phoneNumber: '74444555',
    address: 'Av. Oquendo 567',
    deliveryZone: 'Sur',
    delivery: 'Otro',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['huevo'],
    isActive: true,
    plan: 'Ligero',
    discount: 0,
    contractDate: '2026-04-10',
    startDate: '2026-04-11',
    contractEndDate: '2026-10-10',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-04-10', metadata: { plan: 'Ligero', price: 2000 } }],
  },
  // id: 15
  {
    name: 'Andrés Vega',
    sex: 'male',
    dateOfBirth: '1986-12-24',
    phoneNumber: '75555666',
    address: 'Calle Antezana 890',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: ['diabetes tipo 2'],
    restrictions: ['azúcar', 'harinas refinadas', 'alcohol'],
    isActive: true,
    plan: 'Ejecutivo',
    discount: 0,
    contractDate: '2026-03-05',
    startDate: '2026-03-06',
    contractEndDate: '2026-09-05',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-03-05', metadata: { plan: 'Ejecutivo', price: 1800 } }],
  },
  // id: 16
  {
    name: 'Valeria Medina',
    sex: 'female',
    dateOfBirth: '1994-05-30',
    phoneNumber: '76666777',
    address: 'Av. Circunvalación 340',
    deliveryZone: 'Sur',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['gluten', 'lactosa'],
    isActive: true,
    plan: 'Básico',
    discount: 0,
    contractDate: '2026-05-20',
    startDate: '2026-05-21',
    contractEndDate: '2026-11-19',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-05-20', metadata: { plan: 'Básico', price: 1500 } }],
  },
  // id: 17
  {
    name: 'Pablo Guerrero',
    sex: 'male',
    dateOfBirth: '1982-02-14',
    phoneNumber: '77777888',
    address: 'Calle Lanza 456',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: '9876543',
    businessName: null,
    underlyingDiseases: [],
    restrictions: [],
    isActive: true,
    plan: 'Completo',
    discount: 0,
    contractDate: '2026-02-20',
    startDate: '2026-02-21',
    contractEndDate: '2026-08-20',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-02-20', metadata: { plan: 'Completo', price: 3500 } }],
  },
  // id: 18
  {
    name: 'Daniela Ruiz',
    sex: 'female',
    dateOfBirth: '1996-09-08',
    phoneNumber: '78888999',
    address: 'Av. Libertador 670',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['picante'],
    isActive: true,
    plan: 'Ligero',
    discount: 0,
    contractDate: '2026-05-25',
    startDate: '2026-05-26',
    contractEndDate: '2026-11-24',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-05-25', metadata: { plan: 'Ligero', price: 2000 } }],
  },
  // id: 19
  {
    name: 'Sergio Ramos',
    sex: 'male',
    dateOfBirth: '1984-07-17',
    phoneNumber: '79999000',
    address: 'Calle Punata 123',
    deliveryZone: 'Sur',
    delivery: 'Otro',
    nit: null,
    businessName: null,
    underlyingDiseases: ['hipotiroidismo'],
    restrictions: ['soja', 'yodo excesivo'],
    isActive: true,
    plan: 'Ejecutivo',
    discount: 100,
    contractDate: '2026-04-05',
    startDate: '2026-04-06',
    contractEndDate: '2026-10-05',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-04-05', metadata: { plan: 'Ejecutivo', price: 1800 } }],
  },
  // id: 20
  {
    name: 'Elena Castro',
    sex: 'female',
    dateOfBirth: '1990-11-22',
    phoneNumber: '70000111',
    address: 'Av. Uyuni 890',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['mariscos', 'pescado'],
    isActive: true,
    plan: 'Básico',
    discount: 0,
    contractDate: '2026-03-10',
    startDate: '2026-03-11',
    contractEndDate: '2026-09-10',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-03-10', metadata: { plan: 'Básico', price: 1500 } }],
  },
  // id: 21
  {
    name: 'Eduardo Luna',
    sex: 'male',
    dateOfBirth: '1979-04-25',
    phoneNumber: '71010202',
    address: 'Calle Aroma 340',
    deliveryZone: 'Sur',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: [],
    isActive: true,
    plan: 'Completo',
    discount: 0,
    contractDate: '2026-01-15',
    startDate: '2026-01-17',
    contractEndDate: '2026-07-17',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-01-15', metadata: { plan: 'Completo', price: 3500 } }],
  },
  // id: 22
  {
    name: 'Lucía Vargas',
    sex: 'female',
    dateOfBirth: '1993-06-14',
    phoneNumber: '72020303',
    address: 'Av. Barrientos 560',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['nueces'],
    isActive: true,
    plan: 'Premium',
    discount: 200,
    contractDate: '2026-05-08',
    startDate: '2026-05-09',
    contractEndDate: '2026-11-07',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-05-08', metadata: { plan: 'Premium', price: 4200 } }],
  },
  // id: 23
  {
    name: 'Manuel Cruz',
    sex: 'male',
    dateOfBirth: '1987-01-31',
    phoneNumber: '73030404',
    address: 'Calle Chuquisaca 780',
    deliveryZone: 'Sur',
    delivery: 'Otro',
    nit: null,
    businessName: null,
    underlyingDiseases: ['hipertensión'],
    restrictions: ['sal', 'embutidos'],
    isActive: true,
    plan: 'Ligero',
    discount: 0,
    contractDate: '2026-04-25',
    startDate: '2026-04-26',
    contractEndDate: '2026-10-25',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-04-25', metadata: { plan: 'Ligero', price: 2000 } }],
  },
  // id: 24
  {
    name: 'Camila Flores',
    sex: 'female',
    dateOfBirth: '1998-08-19',
    phoneNumber: '74040505',
    address: 'Av. Petrolera 120',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: [],
    isActive: true,
    plan: 'Básico',
    discount: 0,
    contractDate: '2026-05-28',
    startDate: '2026-05-29',
    contractEndDate: '2026-11-27',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-05-28', metadata: { plan: 'Básico', price: 1500 } }],
  },
  // id: 25
  {
    name: 'Ricardo Soto',
    sex: 'male',
    dateOfBirth: '1981-10-04',
    phoneNumber: '75050606',
    address: 'Calle Ecuador 450',
    deliveryZone: 'Sur',
    delivery: 'La Oliva',
    nit: '3216549',
    businessName: 'Soto Eventos',
    underlyingDiseases: [],
    restrictions: ['lactosa'],
    isActive: true,
    plan: 'Ejecutivo',
    discount: 0,
    contractDate: '2026-03-15',
    startDate: '2026-03-16',
    contractEndDate: '2026-09-15',
    duration: 130,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-03-15', metadata: { plan: 'Ejecutivo', price: 1800 } }],
  },
];

// 3 expiring clients — isActive true, contractEndDate within 5 business days of today
const EXPIRING_CLIENTS = [
  {
    name: 'Sofía Montero',
    sex: 'female',
    dateOfBirth: '1990-08-14',
    phoneNumber: '76111222',
    address: 'Av. Las Américas 340',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['gluten'],
    isActive: true,
    plan: 'Ligero',
    discount: 0,
    contractDate: '2026-03-01',
    startDate: '2026-03-03',
    contractEndDate: '2026-06-05',
    duration: 70,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-03-01', metadata: { plan: 'Ligero', price: 2000 } }],
  },
  {
    name: 'Tomás Quiroga',
    sex: 'male',
    dateOfBirth: '1985-02-20',
    phoneNumber: '77222333',
    address: 'Calle Sucre 890',
    deliveryZone: 'Sur',
    delivery: 'Otro',
    nit: null,
    businessName: null,
    underlyingDiseases: ['hipertensión'],
    restrictions: ['sal', 'embutidos'],
    isActive: true,
    plan: 'Básico',
    discount: 100,
    contractDate: '2026-03-05',
    startDate: '2026-03-06',
    contractEndDate: '2026-06-08',
    duration: 70,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-03-05', metadata: { plan: 'Básico', price: 1500 } }],
  },
  {
    name: 'Mariana Villanueva',
    sex: 'female',
    dateOfBirth: '1993-11-30',
    phoneNumber: '78333444',
    address: 'Av. Blanco Galindo 560',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['lactosa', 'huevo'],
    isActive: true,
    plan: 'Ejecutivo',
    discount: 0,
    contractDate: '2026-03-08',
    startDate: '2026-03-09',
    contractEndDate: '2026-06-09',
    duration: 70,
    suspendedDates: [],
    history: [{ eventType: 'plan_assigned', occurredAt: '2026-03-08', metadata: { plan: 'Ejecutivo', price: 1800 } }],
  },
];

// 5 suspended clients — isActive true, suspendedDates includes today
const SUSPENDED_CLIENTS = [
  {
    name: 'Andrea Morales',
    sex: 'female',
    dateOfBirth: '1992-04-12',
    phoneNumber: '76060707',
    address: 'Av. Melchor Pérez 230',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['carne de cerdo'],
    isActive: true,
    plan: 'Básico',
    discount: 0,
    contractDate: '2026-04-01',
    startDate: '2026-04-02',
    contractEndDate: '2026-07-30',
    duration: 90,
    suspendedDates: [TODAY],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-04-01', metadata: { plan: 'Básico', price: 1500 } },
      { eventType: 'suspended', occurredAt: TODAY, metadata: { suspendedDate: TODAY } },
    ],
  },
  {
    name: 'Alejandro Ríos',
    sex: 'male',
    dateOfBirth: '1988-09-27',
    phoneNumber: '77070808',
    address: 'Calle Chapare 670',
    deliveryZone: 'Sur',
    delivery: 'Otro',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: [],
    isActive: true,
    plan: 'Ligero',
    discount: 100,
    contractDate: '2026-03-25',
    startDate: '2026-03-26',
    contractEndDate: '2026-08-05',
    duration: 95,
    suspendedDates: [TODAY],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-03-25', metadata: { plan: 'Ligero', price: 2000 } },
      { eventType: 'suspended', occurredAt: TODAY, metadata: { suspendedDate: TODAY } },
    ],
  },
  {
    name: 'Gabriela Silva',
    sex: 'female',
    dateOfBirth: '1995-01-08',
    phoneNumber: '78080909',
    address: 'Av. Melchor 890',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: ['celiaquía'],
    restrictions: ['gluten', 'trigo', 'cebada'],
    isActive: true,
    plan: 'Ejecutivo',
    discount: 0,
    contractDate: '2026-02-10',
    startDate: '2026-02-11',
    contractEndDate: '2026-07-15',
    duration: 110,
    suspendedDates: [TODAY],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-02-10', metadata: { plan: 'Ejecutivo', price: 1800 } },
      { eventType: 'suspended', occurredAt: TODAY, metadata: { suspendedDate: TODAY } },
    ],
  },
  {
    name: 'Javier Peña',
    sex: 'male',
    dateOfBirth: '1985-11-16',
    phoneNumber: '79090010',
    address: 'Calle Oruro 340',
    deliveryZone: 'Sur',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['maní'],
    isActive: true,
    plan: 'Completo',
    discount: 0,
    contractDate: '2026-04-20',
    startDate: '2026-04-21',
    contractEndDate: '2026-08-20',
    duration: 90,
    suspendedDates: [TODAY],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-04-20', metadata: { plan: 'Completo', price: 3500 } },
      { eventType: 'suspended', occurredAt: TODAY, metadata: { suspendedDate: TODAY } },
    ],
  },
  {
    name: 'Natalia Jiménez',
    sex: 'female',
    dateOfBirth: '1991-06-03',
    phoneNumber: '70100201',
    address: 'Av. Kanata 560',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['huevo', 'mariscos'],
    isActive: true,
    plan: 'Básico',
    discount: 0,
    contractDate: '2026-05-05',
    startDate: '2026-05-06',
    contractEndDate: '2026-08-05',
    duration: 65,
    suspendedDates: [TODAY],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-05-05', metadata: { plan: 'Básico', price: 1500 } },
      { eventType: 'suspended', occurredAt: TODAY, metadata: { suspendedDate: TODAY } },
    ],
  },
];

// 5 paused clients — isActive false, contractEndDate in the future
const PAUSED_CLIENTS = [
  {
    name: 'Valentina Aguilar',
    sex: 'female',
    dateOfBirth: '1993-03-20',
    phoneNumber: '71020304',
    address: 'Calle Ayacucho 230',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['lácteos'],
    isActive: false,
    plan: 'Ligero',
    discount: 0,
    contractDate: '2026-03-01',
    startDate: '2026-03-02',
    contractEndDate: '2026-09-30',
    duration: 150,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-03-01', metadata: { plan: 'Ligero', price: 2000 } },
      { eventType: 'paused', occurredAt: '2026-05-20', metadata: { remainingDays: 75 } },
    ],
  },
  {
    name: 'Arturo Delgado',
    sex: 'male',
    dateOfBirth: '1977-07-09',
    phoneNumber: '72030405',
    address: 'Av. Ramón Rivero 450',
    deliveryZone: 'Sur',
    delivery: 'Otro',
    nit: '6543219',
    businessName: null,
    underlyingDiseases: ['diabetes', 'hipertensión'],
    restrictions: ['azúcar', 'sal', 'grasas saturadas'],
    isActive: false,
    plan: 'Ejecutivo',
    discount: 200,
    contractDate: '2026-02-05',
    startDate: '2026-02-06',
    contractEndDate: '2026-10-15',
    duration: 175,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-02-05', metadata: { plan: 'Ejecutivo', price: 1800 } },
      { eventType: 'paused', occurredAt: '2026-05-10', metadata: { remainingDays: 110 } },
    ],
  },
  {
    name: 'Claudia Reyes',
    sex: 'female',
    dateOfBirth: '1989-12-01',
    phoneNumber: '73040506',
    address: 'Calle Hamiraya 120',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: [],
    isActive: false,
    plan: 'Básico',
    discount: 0,
    contractDate: '2026-01-25',
    startDate: '2026-01-27',
    contractEndDate: '2026-08-25',
    duration: 150,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-01-25', metadata: { plan: 'Básico', price: 1500 } },
      { eventType: 'paused', occurredAt: '2026-05-01', metadata: { remainingDays: 80 } },
    ],
  },
  {
    name: 'César Molina',
    sex: 'male',
    dateOfBirth: '1983-05-14',
    phoneNumber: '74050607',
    address: 'Av. Virgen de Cotoca 780',
    deliveryZone: 'Sur',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['gluten'],
    isActive: false,
    plan: 'Completo',
    discount: 0,
    contractDate: '2026-04-01',
    startDate: '2026-04-02',
    contractEndDate: '2026-11-01',
    duration: 155,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-04-01', metadata: { plan: 'Completo', price: 3500 } },
      { eventType: 'paused', occurredAt: '2026-05-25', metadata: { remainingDays: 115 } },
    ],
  },
  {
    name: 'Mónica Fuentes',
    sex: 'female',
    dateOfBirth: '1996-02-17',
    phoneNumber: '75060708',
    address: 'Calle Libertad 340',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: ['anemia'],
    restrictions: ['té', 'café'],
    isActive: false,
    plan: 'Premium',
    discount: 400,
    contractDate: '2026-03-10',
    startDate: '2026-03-11',
    contractEndDate: '2026-10-10',
    duration: 155,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-03-10', metadata: { plan: 'Premium', price: 4200 } },
      { eventType: 'paused', occurredAt: '2026-05-15', metadata: { remainingDays: 100 } },
    ],
  },
];

// 10 finalized clients — contractEndDate in the past
const FINALIZED_CLIENTS = [
  {
    name: 'Bernardo Ojeda',
    sex: 'male',
    dateOfBirth: '1976-08-22',
    phoneNumber: '76070809',
    address: 'Av. Patria 230',
    deliveryZone: 'Sur',
    delivery: 'Otro',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: [],
    isActive: false,
    plan: 'Básico',
    discount: 0,
    contractDate: '2025-11-01',
    startDate: '2025-11-03',
    contractEndDate: '2026-03-31',
    duration: 110,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2025-11-01', metadata: { plan: 'Básico', price: 1500 } },
      { eventType: 'finalized', occurredAt: '2026-03-31', metadata: {} },
    ],
  },
  {
    name: 'Paula Espinoza',
    sex: 'female',
    dateOfBirth: '1994-04-05',
    phoneNumber: '77080910',
    address: 'Calle Baptista 450',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['mariscos'],
    isActive: false,
    plan: 'Ligero',
    discount: 0,
    contractDate: '2025-12-01',
    startDate: '2025-12-02',
    contractEndDate: '2026-04-30',
    duration: 110,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2025-12-01', metadata: { plan: 'Ligero', price: 2000 } },
      { eventType: 'finalized', occurredAt: '2026-04-30', metadata: {} },
    ],
  },
  {
    name: 'Ernesto Navarro',
    sex: 'male',
    dateOfBirth: '1981-09-13',
    phoneNumber: '78091011',
    address: 'Av. Heroínas 670',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: '7891234',
    businessName: 'Navarro & Asociados',
    underlyingDiseases: [],
    restrictions: [],
    isActive: false,
    plan: 'Completo',
    discount: 500,
    contractDate: '2025-10-15',
    startDate: '2025-10-17',
    contractEndDate: '2026-02-28',
    duration: 100,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2025-10-15', metadata: { plan: 'Completo', price: 3500 } },
      { eventType: 'plan_changed', occurredAt: '2025-12-01', metadata: { previousPlan: 'Completo', newPlan: 'Completo', newPrice: 3000 } },
      { eventType: 'finalized', occurredAt: '2026-02-28', metadata: {} },
    ],
  },
  {
    name: 'Rocío Cabrera',
    sex: 'female',
    dateOfBirth: '1990-07-28',
    phoneNumber: '79101112',
    address: 'Calle Tarata 120',
    deliveryZone: 'Sur',
    delivery: 'Otro',
    nit: null,
    businessName: null,
    underlyingDiseases: ['colesterol alto'],
    restrictions: ['grasas animales', 'frituras'],
    isActive: false,
    plan: 'Ejecutivo',
    discount: 0,
    contractDate: '2025-09-01',
    startDate: '2025-09-02',
    contractEndDate: '2026-01-31',
    duration: 110,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2025-09-01', metadata: { plan: 'Ejecutivo', price: 1800 } },
      { eventType: 'finalized', occurredAt: '2026-01-31', metadata: {} },
    ],
  },
  {
    name: 'Felipe Paredes',
    sex: 'male',
    dateOfBirth: '1986-03-07',
    phoneNumber: '70111213',
    address: 'Av. Melchor Pérez 890',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: [],
    isActive: false,
    plan: 'Básico',
    discount: 0,
    contractDate: '2026-01-05',
    startDate: '2026-01-06',
    contractEndDate: '2026-05-05',
    duration: 90,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-01-05', metadata: { plan: 'Básico', price: 1500 } },
      { eventType: 'finalized', occurredAt: '2026-05-05', metadata: {} },
    ],
  },
  // finalized with paused/resumed history
  {
    name: 'Gonzalo Ibarra',
    sex: 'male',
    dateOfBirth: '1979-11-19',
    phoneNumber: '71121314',
    address: 'Calle Punata 670',
    deliveryZone: 'Sur',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: ['hipertensión'],
    restrictions: ['sal'],
    isActive: false,
    plan: 'Ligero',
    discount: 100,
    contractDate: '2025-10-01',
    startDate: '2025-10-03',
    contractEndDate: '2026-03-15',
    duration: 115,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2025-10-01', metadata: { plan: 'Ligero', price: 2000 } },
      { eventType: 'paused', occurredAt: '2025-12-10', metadata: { remainingDays: 55 } },
      { eventType: 'resumed', occurredAt: '2025-12-28', metadata: { newContractEndDate: '2026-03-15' } },
      { eventType: 'finalized', occurredAt: '2026-03-15', metadata: {} },
    ],
  },
  {
    name: 'Hugo Vargas',
    sex: 'male',
    dateOfBirth: '1984-02-23',
    phoneNumber: '72131415',
    address: 'Av. América 120',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['huevo'],
    isActive: false,
    plan: 'Completo',
    discount: 0,
    contractDate: '2026-01-10',
    startDate: '2026-01-11',
    contractEndDate: '2026-05-10',
    duration: 90,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-01-10', metadata: { plan: 'Completo', price: 3500 } },
      { eventType: 'finalized', occurredAt: '2026-05-10', metadata: {} },
    ],
  },
  {
    name: 'Ignacia Lara',
    sex: 'female',
    dateOfBirth: '1997-06-30',
    phoneNumber: '73141516',
    address: 'Calle Cochabamba 340',
    deliveryZone: 'Sur',
    delivery: 'Otro',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: ['nueces', 'almendras'],
    isActive: false,
    plan: 'Premium',
    discount: 300,
    contractDate: '2025-11-15',
    startDate: '2025-11-17',
    contractEndDate: '2026-04-15',
    duration: 110,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2025-11-15', metadata: { plan: 'Premium', price: 4200 } },
      { eventType: 'finalized', occurredAt: '2026-04-15', metadata: {} },
    ],
  },
  // finalized with plan change history
  {
    name: 'Jesús Cabrera',
    sex: 'male',
    dateOfBirth: '1982-08-11',
    phoneNumber: '74151617',
    address: 'Av. Blanco Galindo 560',
    deliveryZone: 'Centro',
    delivery: 'La Oliva',
    nit: '2345678',
    businessName: null,
    underlyingDiseases: ['diabetes'],
    restrictions: ['azúcar', 'carbohidratos refinados'],
    isActive: false,
    plan: 'Ejecutivo',
    discount: 0,
    contractDate: '2025-12-15',
    startDate: '2025-12-16',
    contractEndDate: '2026-05-20',
    duration: 115,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2025-12-15', metadata: { plan: 'Ligero', price: 2000 } },
      { eventType: 'plan_changed', occurredAt: '2026-02-01', metadata: { previousPlan: 'Ligero', newPlan: 'Ejecutivo', newPrice: 1800 } },
      { eventType: 'finalized', occurredAt: '2026-05-20', metadata: {} },
    ],
  },
  {
    name: 'Kelvin Montes',
    sex: 'male',
    dateOfBirth: '1993-10-06',
    phoneNumber: '75161718',
    address: 'Calle Antofagasta 780',
    deliveryZone: 'Sur',
    delivery: 'La Oliva',
    nit: null,
    businessName: null,
    underlyingDiseases: [],
    restrictions: [],
    isActive: false,
    plan: 'Básico',
    discount: 0,
    contractDate: '2026-01-20',
    startDate: '2026-01-21',
    contractEndDate: '2026-05-30',
    duration: 95,
    suspendedDates: [],
    history: [
      { eventType: 'plan_assigned', occurredAt: '2026-01-20', metadata: { plan: 'Básico', price: 1500 } },
      { eventType: 'finalized', occurredAt: '2026-05-30', metadata: {} },
    ],
  },
];

// ---------------------------------------------------------------------------
// Seed runner
// ---------------------------------------------------------------------------
async function seed() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    // Insert plans and collect their IDs
    const planIdMap = {};
    for (const plan of PLANS) {
      const { rows } = await client.query(
        `INSERT INTO plans (name, meals, price, "createdAt", "updatedAt")
         VALUES ($1, $2, $3, $4, $4) RETURNING id`,
        [plan.name, plan.meals, plan.price, NOW],
      );
      planIdMap[plan.name] = rows[0].id;
    }

    // Insert all client groups
    const allClients = [
      ...ACTIVE_CLIENTS,
      ...EXPIRING_CLIENTS,
      ...SUSPENDED_CLIENTS,
      ...PAUSED_CLIENTS,
      ...FINALIZED_CLIENTS,
    ];

    for (const c of allClients) {
      // Insert client
      const { rows: clientRows } = await client.query(
        `INSERT INTO clients
           (name, sex, "dateOfBirth", "phoneNumber", address, "deliveryZone", delivery,
            nit, "businessName", "underlyingDiseases", restrictions, "isActive",
            "createdAt", "updatedAt")
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13) RETURNING id`,
        [
          c.name,
          c.sex,
          c.dateOfBirth,
          c.phoneNumber,
          c.address,
          c.deliveryZone,
          c.delivery,
          c.nit,
          c.businessName,
          c.underlyingDiseases,
          c.restrictions,
          c.isActive,
          NOW,
        ],
      );
      const clientId = clientRows[0].id;
      const planId = planIdMap[c.plan];

      // Insert subscription
      await client.query(
        `INSERT INTO subscriptions
           ("clientId", "planId", "contractDate", "startDate", "contractEndDate",
            discount, duration, "suspendedDates", "createdAt", "updatedAt")
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$9)`,
        [
          clientId,
          planId,
          c.contractDate,
          c.startDate,
          c.contractEndDate,
          c.discount,
          c.duration,
          c.suspendedDates,
          NOW,
        ],
      );

      // Insert history events
      for (const event of c.history) {
        await client.query(
          `INSERT INTO client_history ("clientId", "eventType", "occurredAt", metadata)
           VALUES ($1,$2,$3,$4)`,
          [clientId, event.eventType, event.occurredAt, JSON.stringify(event.metadata)],
        );
      }
    }

    await client.query('COMMIT');

    const counts = {
      plans: PLANS.length,
      active: ACTIVE_CLIENTS.length,
      expiring: EXPIRING_CLIENTS.length,
      suspended: SUSPENDED_CLIENTS.length,
      paused: PAUSED_CLIENTS.length,
      finalized: FINALIZED_CLIENTS.length,
    };
    console.log('Seed complete:', counts);
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('Seed failed:', err);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
  }
}

seed();
